### ISSUE TITLE
Includes rendered before content

### ISSUE THREAD

**Issue by kobenauf** [raptorjs/marko#82] opened 2015-06-03 13:37 UTC
With a marko page like this:
`<include template="./header.marko"/>`
`    ${data.bodyText}`
`<include template="./footer.marko"/>`

The rendered result is:
header content
footer content
body content

The expected result is:
header
body
footer

**Comment by patrick-steele-idem** [comment] 2015-06-03 15:52
Hi @kobenauf, I am not able to reproduce the issue so there must be something else that is coming into play. What version of `marko` are you using?

I created a simple project to test with and everything renders as expected:
https://github.com/patrick-steele-idem/marko-issue-82

Please try to reproduce the problem in that project or share your own simple project to reproduce the problem. Thank you.

**Comment by kobenauf** [comment] 2015-06-03 21:40
Thanks for creating that.  This has to be my misunderstanding of what include would do.  Stripping the extra code from my header and footer I found the issue was if I have an open tag in the header (i.e. a `<body>` tag) and a closing tag in the footer (`</body>`), Marko adds a closing tag to the header and drops the closing tag from the footer.  

So it seems each included template has to be a stand-alone template, not depending on HTML tags opened or closed outside of that template.  Is that correct?

**Comment by patrick-steele-idem** [comment] 2015-06-03 22:30
Correct, each standalone template needs to be independent and well-formed HTML since each template is parsed using an HTML parser. In practice this is really not a limitation but it does put a constraint on how to code your templates. I recommend using the layout taglib to piece together your page instead of includes. Please see: https://github.com/raptorjs/marko#layout-taglib

Please let me know if that does or does not work for you. I'm going to go ahead and close this issue, but we can discuss some more here if you would like or in the Gitter chat room: gitter.im/raptorjs/marko

**Closed by patrick-steele-idem** 2015-06-03 22:30 UTC
